name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Check Backend Runs
        run: |
          cd backend
          node app.js
